server:
  port: 9000
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: micro-usuarios
              uri: http://localhost:8080
              predicates:
                - Path=/usuarios/**
            - id: micro-prendas
              uri: http://localhost:8081
              predicates:
                - Path=/prendas/**
            - id: micro-locales
              uri: http://localhost:8082
              predicates:
                - Path=/locales/**
