server:
  port: 9000
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: micro-usuarios
              uri: http://usuarios:8080
              predicates:
                - Path=/usuarios/**
            - id: micro-prendas
              uri: http://prendas:8081
              predicates:
                - Path=/prendas/**
            - id: micro-locales
              uri: http://locales:8082
              predicates:
                - Path=/locales/**
#Cambiar a localhost si se quiere probar en local, sino ejecutar docker-compose