server:
  port: 8888

spring:
  application:
    name:config-server
  cloud:
    config:
      enabled: true
      server:
        native:
          search-locations: classpath:/configuracion
  profiles:
    active: native