spring:
  application:
    name: usuarios
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://config-server:8888
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

      #Cambiar a localhost si se quiere probar en local, sino ejecutar docker-compose